const DAYS=[{id:'mon',label:'Mon',title:'Push',focus:'Chest · Shoulders · Triceps'},{id:'tue',label:'Tue',title:'Pull',focus:'Back · Biceps · Core'},{id:'thu',label:'Thu',title:'Legs',focus:'Quads · Glutes · Calves'},{id:'sat',label:'Sat',title:'Full Body',focus:'Strength · Skills · Core'}];
const LEVELS={beginner:'Beginner',intermediate:'Intermediate',advanced:'Advanced',elite:'Elite'};
const LEVEL_DESC={beginner:'Learn technique and build a base',intermediate:'Build strength and control',advanced:'Increase intensity and skill',elite:'Maximum challenge and volume'};
const EXERCISES={
 push:{name:'Push-up',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pushups.gif',demo:'https://commons.wikimedia.org/wiki/File:Pushups.gif',muscles:['Chest','Triceps','Front delts'],equipment:'Bodyweight',difficulty:2,how:'Keep your body in one straight line. Lower your chest under control, then push the floor away.',progression:['Incline push-up','Push-up','Diamond push-up','Decline push-up','Archer push-up']},
 incline:{name:'Incline push-up',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pushups.gif',demo:'https://commons.wikimedia.org/wiki/File:Pushups.gif',muscles:['Chest','Triceps'],equipment:'Table / counter',difficulty:1,how:'Place your hands on a stable elevated surface and keep your body straight.',progression:['Wall push-up','Incline push-up','Push-up']},
 pike:{name:'Pike push-up',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pike_Push_Ups.gif',demo:'https://commons.wikimedia.org/wiki/File:Pike_Push_Ups.gif',muscles:['Shoulders','Triceps'],equipment:'Bodyweight',difficulty:3,how:'Keep your hips high and lower your head between your hands. Press back up.',progression:['Hands elevated','Floor pike push-up','Feet elevated','Handstand push-up']},
 diamond:{name:'Diamond push-up',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Narrow_Push_Ups.gif',demo:'https://commons.wikimedia.org/wiki/File:Narrow_Push_Ups.gif',muscles:['Triceps','Chest'],equipment:'Bodyweight',difficulty:3,how:'Place your hands close under your chest and lower under control.',progression:['Knee diamond','Diamond push-up','Slow diamond','Decline diamond']},
 dip:{name:'Chair dip',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Bench-dips-1.png',demo:'https://commons.wikimedia.org/wiki/File:Bench-dips-1.png',muscles:['Triceps','Chest'],equipment:'Stable chair',difficulty:2,how:'Use a very stable chair or bench. Bend the elbows and press back up.',progression:['Bent knees','Straight legs','Feet elevated']},
 plank:{name:'Plank',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Plank_exercise.svg',demo:'https://commons.wikimedia.org/wiki/File:Plank_exercise.svg',muscles:['Core','Shoulders'],equipment:'Bodyweight',difficulty:1,how:'Keep ribs down, glutes tight and body straight. Breathe normally.',progression:['Knee plank','Plank','Long-lever plank','RKC plank']},
 row:{name:'Australian row',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Body-row-1.png',demo:'https://commons.wikimedia.org/wiki/File:Body-row-1.png',muscles:['Upper back','Biceps'],equipment:'Low sturdy bar',difficulty:2,how:'Keep the body rigid and pull the chest toward a sturdy horizontal surface.',progression:['Higher bar','Lower bar','Feet elevated']},
 pull:{name:'Pull-up',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pullup.gif',demo:'https://commons.wikimedia.org/wiki/File:Pullup.gif',muscles:['Lats','Biceps','Upper back'],equipment:'Pull-up bar',difficulty:4,how:'Start from a controlled hang and pull your body toward the bar without swinging.',progression:['Dead hang','Scapular pull-up','Negative','Assisted pull-up','Pull-up','Chest-to-bar']},
 negative:{name:'Negative pull-up',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Pullup.gif',demo:'https://commons.wikimedia.org/wiki/File:Pullup.gif',muscles:['Lats','Biceps'],equipment:'Pull-up bar',difficulty:3,how:'Start at the top and lower slowly for 3–5 seconds.',progression:['3 sec negative','5 sec negative','Assisted pull-up']},
 chin:{name:'Chin-up',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Chin-ups-1.png',demo:'https://commons.wikimedia.org/wiki/File:Chin-ups-1.png',muscles:['Biceps','Lats'],equipment:'Pull-up bar',difficulty:3,how:'Use an underhand grip and pull the elbows down without kicking.',progression:['Assisted chin-up','Chin-up','Slow chin-up','Weighted chin-up']},
 raise:{name:'Hanging knee raise',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Legraises.gif',demo:'https://commons.wikimedia.org/wiki/File:Legraises.gif',muscles:['Abs','Hip flexors'],equipment:'Pull-up bar',difficulty:3,how:'Hang with straight arms and raise the knees without swinging.',progression:['Lying knee raise','Hanging knee raise','Straight-leg raise']},
 squat:{name:'Bodyweight squat',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Bodyweight_Squats.gif',demo:'https://commons.wikimedia.org/wiki/File:Bodyweight_Squats.gif',muscles:['Quads','Glutes'],equipment:'Bodyweight',difficulty:1,how:'Sit the hips down between the feet and stand by driving through the whole foot.',progression:['Squat','Pause squat','Tempo squat','Jump squat']},
 tempoSquat:{name:'Tempo squat',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Bodyweight_Squats.gif',demo:'https://commons.wikimedia.org/wiki/File:Bodyweight_Squats.gif',muscles:['Quads','Glutes'],equipment:'Bodyweight',difficulty:2,how:'Use a slow controlled descent, pause briefly, then stand strongly.',progression:['Squat','Tempo squat','Pause squat','Jump squat']},
 lunge:{name:'Reverse lunge',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Lunge-CDC_strength_training_for_older_adults.gif',demo:'https://commons.wikimedia.org/wiki/File:Lunge-CDC_strength_training_for_older_adults.gif',muscles:['Quads','Glutes'],equipment:'Bodyweight',difficulty:2,how:'Step back, keep the torso stable and lower under control.',progression:['Assisted reverse lunge','Reverse lunge','Deficit reverse lunge']},
 bulgarian:{name:'Bulgarian split squat',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Lunge-CDC_strength_training_for_older_adults.gif',demo:'https://commons.wikimedia.org/wiki/File:Lunge-CDC_strength_training_for_older_adults.gif',muscles:['Quads','Glutes'],equipment:'Chair / bench',difficulty:3,how:'Place the rear foot on a stable chair and lower the front leg under control.',progression:['Assisted split squat','Bulgarian split squat','Deficit split squat']},
 calf:{name:'Single-leg calf raise',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Standing-calf-raises-1.gif',demo:'https://commons.wikimedia.org/wiki/File:Standing-calf-raises-1.gif',muscles:['Calves'],equipment:'Bodyweight',difficulty:2,how:'Rise through the ball of the foot and lower slowly.',progression:['Two-leg calf raise','Single-leg calf raise','Deficit single-leg raise']},
 bridge:{name:'Glute bridge',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Bridge_exercise.svg',demo:'https://commons.wikimedia.org/wiki/File:Bridge_exercise.svg',muscles:['Glutes','Hamstrings'],equipment:'Bodyweight',difficulty:1,how:'Drive the hips up and squeeze the glutes. Avoid arching the lower back.',progression:['Bridge','Pause bridge','Single-leg bridge']},
 hollow:{name:'Hollow body hold',media:'https://commons.wikimedia.org/wiki/Special:Redirect/file/GMFT3-3_making_hollow_body.jpg',demo:'https://commons.wikimedia.org/wiki/File:GMFT3-3_making_hollow_body.jpg',muscles:['Core'],equipment:'Bodyweight',difficulty:3,how:'Press the lower back into the floor and hold the body in a shallow curved shape.',progression:['Tuck hold','One-leg hollow','Hollow hold']}
};
const PLANS={
 mon:{beginner:[['Incline push-ups','3 × 8–12','incline'],['Push-ups','3 × 5–10','push'],['Plank','3 × 20–40 sec','plank'],['Chair dips','2 × 8–12','dip']],intermediate:[['Push-ups','4 × 8–15','push'],['Pike push-ups','3 × 6–12','pike'],['Diamond push-ups','3 × 6–12','diamond'],['Chair dips','3 × 8–15','dip'],['Plank','3 × 30–60 sec','plank']],advanced:[['Diamond push-ups','4 × 8–15','diamond'],['Pike push-ups','4 × 8–15','pike'],['Chair dips','4 × 10–15','dip'],['Push-ups','3 × 15–25','push'],['Plank','3 × 45–75 sec','plank']],elite:[['Diamond push-ups','5 × 10–20','diamond'],['Pike push-ups','4 × 10–18','pike'],['Chair dips','4 × 12–20','dip'],['Push-ups','3 × 20–30','push'],['Plank','4 × 60–90 sec','plank']]},
 tue:{beginner:[['Australian rows','3 × 8–12','row'],['Negative pull-ups','3 × 3','negative'],['Chin-ups','2 × 3–6','chin'],['Hanging knee raises','2 × 6–10','raise']],intermediate:[['Pull-ups','4 × 3–10','pull'],['Australian rows','4 × 8–15','row'],['Negative pull-ups','3 × 3–6','negative'],['Chin-ups','3 × 4–10','chin'],['Hanging knee raises','3 × 8–15','raise']],advanced:[['Pull-ups','5 × 6–12','pull'],['Chin-ups','4 × 6–12','chin'],['Australian rows','4 × 12–20','row'],['Hanging knee raises','4 × 10–18','raise']],elite:[['Pull-ups','5 × 10–15','pull'],['Chin-ups','4 × 10–15','chin'],['Australian rows','4 × 15–25','row'],['Hanging knee raises','4 × 15–25','raise']]},
 thu:{beginner:[['Bodyweight squats','3 × 10–15','squat'],['Reverse lunges','2 × 6–10 / leg','lunge'],['Glute bridges','3 × 10–15','bridge'],['Calf raises','3 × 12–20 / leg','calf']],intermediate:[['Bodyweight squats','4 × 10–20','squat'],['Reverse lunges','3 × 8–15 / leg','lunge'],['Bulgarian split squats','3 × 8–15 / leg','bulgarian'],['Single-leg calf raises','4 × 12–20 / leg','calf'],['Glute bridges','3 × 12–20','bridge'],['Plank','3 × 40–60 sec','plank']],advanced:[['Tempo squats','4 × 12–20','tempoSquat'],['Bulgarian split squats','4 × 10–15 / leg','bulgarian'],['Reverse lunges','3 × 12–18 / leg','lunge'],['Single-leg calf raises','4 × 15–25 / leg','calf'],['Glute bridges','4 × 15–25','bridge']],elite:[['Tempo squats','5 × 15–25','tempoSquat'],['Bulgarian split squats','5 × 12–20 / leg','bulgarian'],['Reverse lunges','4 × 15–20 / leg','lunge'],['Single-leg calf raises','5 × 20–30 / leg','calf'],['Glute bridges','4 × 20–30','bridge']]},
 sat:{beginner:[['Incline push-ups','3 × 8–12','incline'],['Australian rows','3 × 8–12','row'],['Bodyweight squats','3 × 10–15','squat'],['Glute bridges','2 × 12–15','bridge'],['Plank','2 × 20–40 sec','plank']],intermediate:[['Push-ups','3 × 8–15','push'],['Pull-ups','3 × 4–10','pull'],['Bulgarian split squats','3 × 8–12 / leg','bulgarian'],['Pike push-ups','3 × 6–12','pike'],['Hanging knee raises','3 × 8–15','raise'],['Hollow body hold','3 × 20–40 sec','hollow']],advanced:[['Diamond push-ups','4 × 8–15','diamond'],['Pull-ups','4 × 6–12','pull'],['Bulgarian split squats','4 × 10–15 / leg','bulgarian'],['Pike push-ups','4 × 8–15','pike'],['Hanging knee raises','4 × 10–18','raise'],['Hollow body hold','3 × 30–50 sec','hollow']],elite:[['Diamond push-ups','5 × 10–20','diamond'],['Pull-ups','5 × 8–15','pull'],['Bulgarian split squats','5 × 12–20 / leg','bulgarian'],['Pike push-ups','4 × 10–18','pike'],['Hanging knee raises','4 × 15–25','raise'],['Hollow body hold','4 × 40–60 sec','hollow']]}}
};
let currentDay=localStorage.getItem('ct-day')||'mon';let level=localStorage.getItem('ct-difficulty')||'intermediate';let state=JSON.parse(localStorage.getItem('ct-state')||'{}');
const REST_KEY='ct-rest-duration';let restDuration=Number(localStorage.getItem(REST_KEY))||90;let restRemaining=restDuration;let restTimer=null;let restRunning=false;let restPaused=false;
const esc=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const key=i=>`${currentDay}-${level}-${i}`;function save(){localStorage.setItem('ct-day',currentDay);localStorage.setItem('ct-difficulty',level);localStorage.setItem('ct-state',JSON.stringify(state));localStorage.setItem(REST_KEY,String(restDuration));}
function beep(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=880;o.type='sine';g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.18,c.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.15);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.16);setTimeout(()=>c.close(),250)}catch(e){}}
function format(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function updateTimer(){const d=document.getElementById('timerDisplay');if(d)d.textContent=format(restRemaining);const start=document.getElementById('timerStart');if(start)start.textContent=restRunning?(restPaused?'Resume':'Pause'):'Start';const reset=document.getElementById('timerReset');if(reset)reset.hidden=!restRunning;const presets=document.querySelectorAll('.timer-preset');presets.forEach(b=>{b.classList.toggle('active',Number(b.dataset.seconds)===restDuration);b.disabled=restRunning});if(d)d.classList.toggle('finished',restRemaining===0)}
function finishTimer(){clearInterval(restTimer);restTimer=null;restRunning=false;restPaused=false;restRemaining=0;updateTimer();beep();setTimeout(beep,220);if(navigator.vibrate)navigator.vibrate([100,80,180]);setTimeout(()=>{restRemaining=restDuration;updateTimer()},1300)}
function tick(){if(!restRunning||restPaused)return;restRemaining=Math.max(0,restRemaining-1);if(restRemaining>0&&restRemaining<=3)beep();if(restRemaining===0)finishTimer();else updateTimer()}
function startTimer(){if(restRunning){restPaused=!restPaused;updateTimer();return}restRemaining=restDuration;restRunning=true;restPaused=false;updateTimer();beep();clearInterval(restTimer);restTimer=setInterval(tick,1000)}
function resetTimer(){clearInterval(restTimer);restTimer=null;restRunning=false;restPaused=false;restRemaining=restDuration;updateTimer()}
function chooseRest(s){restDuration=s;localStorage.setItem(REST_KEY,String(s));resetTimer()}
function media(e){return `<div class="media-frame"><img src="${e.media}" alt="Demonstration of ${esc(e.name)}" loading="lazy"><div class="media-fallback" hidden><strong>${esc(e.name)}</strong><span>Demo unavailable</span><a href="${e.demo}" target="_blank" rel="noopener">Open demonstration</a></div><div class="media-credit">Wikimedia Commons</div></div>`}
function render(){const d=DAYS.find(x=>x.id===currentDay),items=PLANS[currentDay][level]||[],done=items.filter((_,i)=>state[key(i)]?.exerciseDone).length,pct=Math.round(done/items.length*100);document.getElementById('tabs').innerHTML=DAYS.map(x=>`<button class="tab ${x.id===currentDay?'active':''}" data-day="${x.id}">${x.label}<br>${x.title}</button>`).join('');document.getElementById('stats').innerHTML=`<div class="stat"><div class="stat-label">Exercises</div><div class="stat-value">${items.length}</div></div><div class="stat"><div class="stat-label">Completed</div><div class="stat-value">${done}/${items.length}</div></div><div class="stat wide"><div class="stat-label">Progress</div><div class="progress-wrap"><div class="progress-bar" style="width:${pct}%"></div></div><div class="hint">${pct}% complete · ${d.focus}</div></div>`;document.getElementById('workout').innerHTML=items.map((it,i)=>{const[e,target,id]=it,x=EXERCISES[id],s=state[key(i)]||{},sets=parseInt(target)||3,isTimed=/sec/i.test(target),stars='★'.repeat(x.difficulty)+'☆'.repeat(5-x.difficulty);return `<article class="exercise ${s.open?'open':''}" data-index="${i}"><div class="row"><div><div class="name">${esc(e)}</div><div class="target">${esc(target)}</div></div><button class="btn extend" data-index="${i}">${s.open?'Collapse':'Extend'}</button></div><div class="details">${media(x)}<div class="meta-grid"><div><span>Difficulty</span><strong>${stars}</strong></div><div><span>Equipment</span><strong>${esc(x.equipment)}</strong></div></div><div class="chips">${x.muscles.map(m=>`<span>${esc(m)}</span>`).join('')}</div><div class="tip"><strong>How to:</strong> ${esc(x.how)}</div><div class="progression"><strong>Progression</strong>${x.progression.map((p,j)=>`<span class="step">${esc(p)}</span>${j<x.progression.length-1?'<span class="arrow">→</span>':''}`).join('')}</div><div class="sets">${Array.from({length:sets},(_,j)=>`<label>Set ${j+1}<input class="rep" data-set="${j}" inputmode="numeric" value="${esc(s.reps?.[j]||'')}" placeholder="${isTimed?'sec':'reps'}"><button class="set-done ${s.setsDone?.[j]?'done':''}" data-set="${j}" type="button">${s.setsDone?.[j]?'Done ✓':'Done'}</button></label>`).join('')}</div><label class="check"><input class="done" type="checkbox" ${s.exerciseDone?'checked':''}> Exercise completed</label></div></article>`}).join('');bind();updateTimer();}
function completeSet(i,j,button){const k=key(i),s=state[k]||{},setsDone=[...(s.setsDone||[])];setsDone[j]=!setsDone[j];state[k]={...s,setsDone};save();render();if(setsDone[j]){startTimer();const next=document.querySelector(`.exercise[data-index="${i}"] .set-done[data-set="${j+1}"]`);if(next)setTimeout(()=>next.scrollIntoView({behavior:'smooth',block:'center'}),200)}}
function bind(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{currentDay=b.dataset.day;save();render()});document.querySelectorAll('.extend').forEach(b=>b.onclick=()=>{const i=+b.dataset.index,k=key(i);state[k]={...(state[k]||{}),open:!state[k]?.open};save();render()});document.querySelectorAll('.done').forEach(b=>b.onchange=()=>{const i=+b.closest('.exercise').dataset.index,k=key(i);state[k]={...(state[k]||{}),exerciseDone:b.checked};save();render()});document.querySelectorAll('.rep').forEach(inp=>inp.oninput=()=>{const i=+inp.closest('.exercise').dataset.index,k=key(i),s=state[k]||{},reps=[...(s.reps||[])];reps[+inp.dataset.set]=inp.value;state[k]={...s,reps};save()});document.querySelectorAll('.set-done').forEach(b=>b.onclick=()=>completeSet(+b.closest('.exercise').dataset.index,+b.dataset.set,b));document.querySelectorAll('.media-frame img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true;img.parentElement.querySelector('.media-fallback').hidden=false}));}
function renderDifficulty(){document.getElementById('difficultyDescription').textContent=LEVEL_DESC[level];document.getElementById('difficultyPicker').innerHTML=Object.entries(LEVELS).map(([id,name])=>`<button class="difficulty-option ${id===level?'active':''}" data-level="${id}" type="button">${name}</button>`).join('');document.querySelectorAll('.difficulty-option').forEach(b=>b.onclick=()=>{level=b.dataset.level;save();renderDifficulty();render()})}
function initTimer(){document.querySelectorAll('.timer-preset').forEach(b=>b.onclick=()=>chooseRest(Number(b.dataset.seconds)));document.getElementById('timerStart').onclick=startTimer;document.getElementById('timerReset').onclick=resetTimer;updateTimer()}
renderDifficulty();render();initTimer();